---
output:
  pdf_document:
header-includes:
- \usepackage{caption}
- \captionsetup[figure]{labelformat=empty}
- \captionsetup[table]{labelformat=empty}
---

```{r Load libraries, echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE}
library(dplyr) #For handling fata 
library(sf) #For handling coordinates and plotting
library(scales) #For plotting (decimals on axes)
library(lubridate) #To operate with dates
library(tidyr) #Reshape data (wide format)
library(stringr) #Fix/modify strings
library(forcats)
library(readr)
#Load libraries for plotting
library(giscoR) #Maps
library(ggstar) #cool shapes as points
library(ggplot2) #general plotting
library(ggtree) #phylo trees
library(ggpattern) #cool shapes in barplots
library(patchwork) #plot organisation
library(cowplot) #plot organisation
library(viridis) #colours
library(ggnewscale)
library(ggtreeExtra)
library(kableExtra)

```


```{r echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE,dpi= 1400, out.width="95%", fig.width=10, fig.height=10}

#Read data
tree_family_interactions= readRDS("../../Data/Manuscript_info/bee_phylo.RData")
d1 = readRDS("../../Data/Manuscript_info/bee_data.RData")
n = readRDS("../../Data/Manuscript_info/node_data.RData")


tree_family_interactions@data$Spp_number_Europe = log(tree_family_interactions@data$Spp_number_Europe + 1)
#Circular layour
ggtree(tree_family_interactions, size=0.6, open.angle=1, alpha=1)+ 
geom_tippoint(aes(size= Interactions, fill = Interactions), color="black", shape=21) +
geom_tiplab(linetype='dashed', linesize=.05, offset = 0.065, size=2.9, fontface=1) +
scale_size(range = c(0,4.5), guide = 'none', breaks = c(3, 6, 9))  +
scale_fill_continuous(type = "viridis", direction=-1,breaks = c(3, 6, 9)) + 
 guides(
    fill = guide_legend(override.aes = list(size=c(3/1.7, 6/1.7, 9/1.7)),
      title.hjust = 0.5,
      keywidth = 1,                        # Increase width of fill legend keys
      keyheight = 2,                     # Increase height of fill legend keys
      label.theme = element_text(size = 14) # Scale up fill label text size
    ),
    size = guide_legend(
      title.hjust = 0.5,
      keywidth = 1,                        # Increase width of size legend keys
      keyheight = 2,                     # Increase height of size legend keys
      label.theme = element_text(size = 14) # Scale up size label text size
    )) +
new_scale_fill() +
geom_fruit(data = d1, geom=geom_bar,
                    mapping=aes(y=Genus1, x=Percent, fill = fam_group),
                    pwidth=0.13, 
                    orientation="y", 
                    stat="identity",
                    color="black",
                    offset = 0.148,
            axis.params=list(
                         axis = "x",
                         text.size  = 2.5,
                         hjust  = 1.2,
                         vjust = 0.5,
                         nbreak = 3,
                         fontface = 2
                     ),
         grid.params=list()) +
guides(fill = "none")+
scale_fill_manual(values = c(a = "tan2", b = "lightgrey"), guide = "none")+
geom_fruit(geom=geom_bar,
                    mapping=aes(y=label, x=Spp_number_Europe),
                    pwidth=0.12, 
                    orientation="y", 
                    stat="identity",
                    color="black",
                    offset = 0,
            axis.params=list(
                         axis = "x",
                         text.size  = 2.5,
                         hjust  = -0.2,
                         vjust = 0.5,
                         nbreak = 3,
                         fontface = 2
                     ),
         grid.params=list()) +
annotate("text", x = 14.35, y = 70, label = "EuPPollNet spp\n coverage (%)", size= 3, fontface= "bold") +
annotate("text", x = 16, y = 70, label = "European\n species", size= 3, fontface= "bold")+
annotate("text", x = 12.2, y = 70, label = "EuPPollNet\n interactions", size= 3, fontface= "bold")+ 
new_scale_fill() +
geom_point2(aes(subset=node==131), color='orange', size=3) +
geom_point2(aes(subset=node==84), color='orange', size=3) +
geom_point2(aes(subset=node==73), color='orange', size=3) +
geom_point2(aes(subset=node==74), color='orange', size=3) +
geom_point2(aes(subset=node==111), color='orange', size=3)+
geom_point2(aes(subset=node==91), color='orange', size=3) +
annotate("text", x = 9.45, y = 2.7, label = "Melittidae", size= 3)+
annotate("text", x = 7.3, y = 6.4, label = "Andrenidae", size= 3)+
annotate("text", x = 10.4, y = 12.4, label = "Colletidae", size= 3)+
annotate("text", x = 5.45, y = 17.3, label = "Halictidae", size= 3)+
annotate("text", x = 2.25, y = 26.8, label = "Megachilidae", size= 3)+
annotate("text", x = 2.5, y = 51, label = "Apidae", size= 3) +
coord_cartesian(clip = "off")+
 theme(
    legend.margin = margin(0, 0, 0, 0),                   # No additional margin around the legend
    legend.spacing.y = unit(0.2, "cm"),                  # Very small vertical spacing
    plot.margin = margin(4, 0, 10, 0),                     # Adjust plot margins as needed
    legend.position = c(0.6, -0.005),                           # Position the legend
    legend.direction = "horizontal",                        # Legend items in a single row
    legend.key.size = unit(0.8, 'cm'),                    # Smaller key size for compactness
    legend.spacing.x = unit(0.05, "cm"),                   # Minimal horizontal spacing
    legend.text = element_text(size = 12),                 # Legend text size
    legend.title = element_text(size = 16)                 # Legend title size
  )


```

