---
output:
  pdf_document:
header-includes:
- \usepackage{caption}
- \captionsetup[figure]{labelformat=empty}
- \captionsetup[table]{labelformat=empty}
---


```{r Load libraries, echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE}
library(dplyr) #For handling fata 
library(ggplot2) #For plotting
library(giscoR) #For plotting
library(sf) #For handling coordinates and plotting
library(patchwork)#For plotting
library(ggstar) #For plotting (cool shapes)
library(scales) #For plotting (decimals on axes)
library(lubridate) #To operate with dates
library(tidyr) #Reshape data (wide format)
library(stringr) #Fix/modify strings
library(forcats)
library(viridis)

```


```{r echo=FALSE, message=FALSE, cache=FALSE, warning=FALSE, out.width="95%", fig.width=4.5, fig.height=8, fig.align='center'}



#Read data
data = readRDS("../../Data/Working_files/Interactions_uncounted.rds")%>% 
mutate(Network_id = paste0(Study_id, Network_id))  


library(ggforce)

#Filter out 2 bioregions that only have a small study with data of a single day
data = data %>% 
filter(!Bioregion == "Steppic") %>% 
filter(!Bioregion == "Pannonian") 

#Prepare orders for filtering
main_orders = c("Hymenoptera", "Lepidoptera", "Coleoptera", "Diptera")

#Karise is a very large study that only sampled bumblebees and
#is providing unrealistic results for the Boreal region
#Filter out
#Maybe add to caption?
data1 = data %>% 
filter(!Study_id == "13_Karise")

#Check number of studies by habitat
habitat = data1 %>% 
select(Study_id, EuPPollNet_habitat) %>% 
distinct() %>%  
group_by(EuPPollNet_habitat) %>% 
summarise(Habitat_count = n()) 
#Check number of studies by bioregion
bioregion = data1 %>% 
select(Study_id, Bioregion) %>% 
distinct() %>%  
group_by(Bioregion) %>% 
summarise(Bioregion_count = n()) 
#Check pols by habitat
pollinator_percent = data1 %>%
group_by(EuPPollNet_habitat, Pollinator_order) %>%
filter(Pollinator_accepted_name!= "Apis mellifera") %>% 
filter(Pollinator_order %in% main_orders) %>% 
summarise(count = n()) %>%
group_by(EuPPollNet_habitat) %>%
mutate(Proportion = count/sum(count)) %>%
select(-count) 
#Check pols by bioregion
pollinator_percent_bio = data1 %>%
group_by(Bioregion, Pollinator_order) %>%
filter(Pollinator_accepted_name!= "Apis mellifera") %>% 
filter(Pollinator_order %in% main_orders) %>% 
summarise(count = n()) %>%
group_by(Bioregion) %>%
mutate(Proportion = count/sum(count)) %>%
select(-count) 
#Preparing datasets for horizontal plot
a1 = habitat %>% 
mutate(Group = "Habitat") %>% 
rename(Habitat = EuPPollNet_habitat) %>% 
rename(Count = Habitat_count)

b1 = bioregion %>% 
mutate(Group = "Bioregion") %>% 
rename(Habitat = Bioregion) %>% 
rename(Count = Bioregion_count)

#Bind datasets
c1 = bind_rows(a1,b1)

#Create datasets and rename cols
a2 = pollinator_percent_bio %>% 
mutate(Group = "Bioregion") %>% 
rename(Habitat = Bioregion) 

b2 = pollinator_percent %>% 
mutate(Group = "Habitat") %>% 
rename(Habitat = EuPPollNet_habitat)
#Bind rows
c2 = bind_rows(a2, b2) 

#Prepare to set ordered labels
l2 = c2 %>% 
filter(Pollinator_order == "Hymenoptera") %>% 
arrange((Proportion)) %>% 
pull(Habitat)
#Set order of labels
c2$Habitat = factor(c2$Habitat, levels = l2)

#Set the right order of labels
c2$Pollinator_order = factor(c2$Pollinator_order, levels = c("Hymenoptera", "Diptera", "Lepidoptera", "Coleoptera"))


p1 = ggplot(c2, 
aes(fill=Pollinator_order, y=Proportion, x=Habitat)) + 
geom_bar(position = position_stack(reverse = TRUE), stat="identity")+
theme_bw() +
theme(legend.position = "bottom",
      plot.margin=unit(c(0,0,0,0), "mm"),
      legend.text = element_text(size=6),
      legend.key.size = unit(2, "mm"),
      legend.spacing.y = unit(0.1, "cm"),
       legend.box.spacing = unit(0, "pt"),
      axis.title = element_text(face = "bold", size = 7),
      axis.text = element_text(size=6),
      panel.border = element_rect(size=1)) +
xlab(NULL) +
ylab("Proportion of species") +
scale_y_continuous(breaks = c(0.25, 0.5,0.75), labels = c("0.25", "0.5","0.75"))+
theme(strip.text.x = element_text(size = 10, face = "bold"),
    strip.background = element_rect(
color=NA, fill=NA, size=0.5, linetype="solid")) +
scale_fill_manual(values = viridis(4),
                  name = NULL) +
coord_flip(expand = FALSE) +
facet_wrap(~ factor(Group, levels=c("Habitat","Bioregion")), space = "free_y", scales = "free") +
guides(fill=guide_legend(nrow=2,byrow=TRUE)) 

#Unify labels
c1$Habitat = factor(c1$Habitat, levels = l2)

#Create barplot on the side
p2 =ggplot(c1, aes(Habitat, Count)) +
geom_col(fill = "gray25",width = 0.9, color="black", linewidth = 0.4) +
theme_light() +
theme(plot.margin=unit(c(0,0,0,0), "mm"),
      axis.ticks.y = element_blank(), 
      axis.ticks.x = element_line(color="black"),
  axis.text.y = element_blank(), 
      strip.text.x = element_text(size=12),
      strip.background = element_rect(
color=NA, fill=NA, size=0.5, linetype="solid"),
  axis.title = element_text(face = "bold", size = 7),
axis.text = element_text(size=6)) +
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(),
panel.border = element_blank(),
axis.line = element_line(color = 'black'),
plot.margin = margin(0,0,0,0)) +
scale_y_continuous(breaks = c(0, 10,20), labels = c("0", "10","20"), limits = c(0,30))+
xlab(NULL) +
ylab("Number of studies")+
theme(legend.position = "none")+
coord_flip(expand = F) +
facet_wrap(~ factor(Group, levels=c("Habitat","Bioregion")), space = "free_y", scales = "free")


#Plot panel
p1 + p2 + plot_layout(widths = c(4,2, 2.5),heights= c(10,10,4), ncol=2) 


```
